import { promises as fs } from "node:fs";
import path from "node:path";

import type { DailyLifeRecord, DailyPoem, DreamRecord, InputPoemsAnalysis, MemoryIndex, MemoryReport, MemoryTrace, MemoryTraceFile, PersonalitySettings, RssSource, SiteSettings, SourceBundle, UcuBedenState, VisualMetadata, World, YearlyReport } from "./types";

export const rootDir = process.cwd();
export const storagePaths = { poemsInput:"poems_input", world:"data/world/ucu_beden_world.json", state:"data/state/ucu_beden_state.json", generatedPoems:"data/generated_poems", dailyLife:"data/daily_life", dreams:"data/dreams", visuals:"data/visuals", yearlyReports:"data/yearly_reports", sources:"data/sources", memoryTraces:"data/memory/traces", memoryIndex:"data/memory/index.json", memoryReport:"data/memory/report.json", siteSettings:"data/settings/site_settings.json", personalitySettings:"data/settings/personality_settings.json", customCode:"data/settings/custom_code.html", rssSources:"data/settings/rss_sources.json", inputAnalysis:"data/analysis/input_poems_analysis.json", vocabularyMemory:"data/analysis/vocabulary_memory.json", imageMutations:"data/analysis/image_mutations.json" } as const;
const dataDirs=["poems_input","data/world","data/state","data/generated_poems","data/daily_life","data/dreams","data/visuals","data/yearly_reports","data/sources","data/memory","data/memory/traces","data/settings","data/analysis"];
export function resolvePath(relativePath:string):string{return path.join(rootDir,relativePath)}
export async function ensureDataDirs():Promise<void>{await Promise.all(dataDirs.map((dir)=>fs.mkdir(resolvePath(dir),{recursive:true})))}
export async function pathExists(relativePath:string):Promise<boolean>{try{await fs.access(resolvePath(relativePath));return true}catch{return false}}
export async function readJsonFile<T>(relativePath:string,fallback:T):Promise<T>{try{return JSON.parse(await fs.readFile(resolvePath(relativePath),"utf8")) as T}catch{return fallback}}
export async function writeJsonFile(relativePath:string,data:unknown):Promise<void>{const absolutePath=resolvePath(relativePath);await fs.mkdir(path.dirname(absolutePath),{recursive:true});await fs.writeFile(absolutePath,`${JSON.stringify(data,null,2)}\n`,"utf8")}
export async function readTextFile(relativePath:string):Promise<string>{return fs.readFile(resolvePath(relativePath),"utf8")}
export async function readOptionalTextFile(relativePath:string):Promise<string>{try{return await readTextFile(relativePath)}catch{return ""}}
export async function writeTextFile(relativePath:string,text:string):Promise<void>{const absolutePath=resolvePath(relativePath);await fs.mkdir(path.dirname(absolutePath),{recursive:true});await fs.writeFile(absolutePath,text,"utf8")}
export async function listFiles(relativeDir:string,extension:string):Promise<string[]>{try{const entries=await fs.readdir(resolvePath(relativeDir),{withFileTypes:true});return entries.filter((entry)=>entry.isFile()&&entry.name.toLocaleLowerCase("tr").endsWith(extension)).map((entry)=>path.join(relativeDir,entry.name).replaceAll("\\","/")).sort()}catch{return []}}
export async function listGeneratedPoems():Promise<DailyPoem[]>{const files=await listFiles(storagePaths.generatedPoems,".json");const poems=await Promise.all(files.map((file)=>readJsonFile<DailyPoem|null>(file,null)));return poems.filter((poem):poem is DailyPoem=>poem!==null).sort((a,b)=>a.date.localeCompare(b.date))}
export async function getLatestPoem():Promise<DailyPoem|null>{return (await listGeneratedPoems()).at(-1)??null}
export async function readDailyLife(date:string):Promise<DailyLifeRecord|null>{return readJsonFile<DailyLifeRecord|null>(`${storagePaths.dailyLife}/${date}.json`,null)}
export async function listDreams():Promise<DreamRecord[]>{const files=await listFiles(storagePaths.dreams,".json");const dreams=await Promise.all(files.map((file)=>readJsonFile<DreamRecord|null>(file,null)));return dreams.filter((dream):dream is DreamRecord=>dream!==null).sort((a,b)=>a.date.localeCompare(b.date))}
export async function getLatestDream():Promise<DreamRecord|null>{return (await listDreams()).at(-1)??null}
export async function readVisual(date:string,type:"poem"|"dream"):Promise<VisualMetadata|null>{return readJsonFile<VisualMetadata|null>(`${storagePaths.visuals}/${date}-${type}.json`,null)}
export async function readWorld():Promise<World>{return readJsonFile<World>(storagePaths.world,{home:{city:"İstanbul",district:"Kadıköy / Osmanağa",building:"apartman detayı gizli",apartment_type:"1+1",size_m2:35,building_feel:"mütevazı, yeni bir bina",rooms:{living_room:{description:"mutfakla birleşik salon",objects:["tek gri koltuk","üzerinde mavi bir figür olan halı","bilgisayar"],habits:["koltukta uzanmayı seviyor"]},bedroom:{description:"oldukça küçük yatak odası",objects:["çift kişilik sayılabilecek küçük bir yatak"],habits:["dar odada daha içe kapanık şiirler yazıyor"]}}},walking_routes:[]})}
export async function readState():Promise<UcuBedenState>{const fallback:UcuBedenState={name:"UCU BEDEN",generated_days:0,age_months:0,last_generated_date:null,last_mood:null,mood_history:[],dominant_words:[],obsessions:[],avoided_words:[],recurring_images:[],memory_density:0,home_memory:{frequent_locations:[],object_fixations:[],recent_body_states:[]},walk_memory:{frequent_segments:[],seen_objects:[],route_mood_associations:[]},external_memory:{recurring_source_words:[],recent_learning_fragments:[],source_mood_history:[]},poetic_drift:{style_notes:"Henüz kendi şiir hafızasını toplamaya başladı.",recent_changes:[],things_it_is_forgetting:[],things_it_keeps_returning_to:[]}};const state=await readJsonFile<Partial<UcuBedenState>>(storagePaths.state,{});return{...fallback,...state,external_memory:state.external_memory??fallback.external_memory}}
export async function readInputAnalysis():Promise<InputPoemsAnalysis>{return readJsonFile<InputPoemsAnalysis>(storagePaths.inputAnalysis,{files:[],global:{poem_count:0,word_count:0,dominant_words:[],image_fields:[],food_images:[],body_images:[],animal_images:[],city_images:[],absurd_fragments:[],repeated_phrases:[],tone:["gündelik","absürt","bedensel"],rhythm_notes:"Kullanıcı şiirleri analiz edilince ritim notları burada oluşur.",style_notes:"Gündelik olanla absürt olan iç içe geçebilir.",taboo_copying_rules:"Do not reproduce full lines from input poems."}})}
export async function readSiteSettings():Promise<SiteSettings>{const settings=await readJsonFile<Partial<SiteSettings>>(storagePaths.siteSettings,{});return{theme:settings.theme==="sims2000"||settings.theme==="minimal"||settings.theme==="fresh90s"?settings.theme:"fresh90s",showMoodDots:settings.showMoodDots??true,showFooterDedication:settings.showFooterDedication??true}}
export async function readPersonalitySettings():Promise<PersonalitySettings>{return readJsonFile<PersonalitySettings>(storagePaths.personalitySettings,{hidden_voice_traits:{dry_sarcasm:.68,absurd_domestic_humor:.82,gentle_passive_aggression:.44,panic_comedy:.71,sentimental_leak:.37},tone_balance:{absurd_domestic:.6,dry_sarcasm:.25,sentimental_leak:.15},publicly_visible:false,private_prompt_note:"UCU BEDEN'in şiirsel karakterinde arka planda çalışan kuru, hafif sarkastik ve gündelik absürt bir damar olmalı; bu özellik arayüzde görünmemeli, sadece üretim dilini etkilemelidir.",hidden_voice_rules:["Sarkazm kaba, saldırgan veya stand-up punchline gibi olmamalı.","Ses kuru, gündelik, içten içe alaycı, hafif bıkkın, bazen çocukça, bazen pasif-agresif kalmalı.","UCU BEDEN dünyaya doğrudan öfkelenmek yerine nesnelerle ve küçük gözlemlerle dalga geçmeli.","Haberleri politik slogan yapma; dünyanın saçmalığını ev nesnelerine, yürüyüşe, yemeklere ve bedene sızdır.","Sarkazm şiirin yüzeyinde bağırmasın; alttan çalışsın.","Dünyayla dalga geç ama tamamen kalpsiz olma."]})}
export async function readRssSources():Promise<RssSource[]>{return readJsonFile<RssSource[]>(storagePaths.rssSources,[])}
export async function listYearlyReports():Promise<YearlyReport[]>{const files=await listFiles(storagePaths.yearlyReports,".json");const reports=await Promise.all(files.map((file)=>readJsonFile<YearlyReport|null>(file,null)));return reports.filter((report):report is YearlyReport=>report!==null).sort((a,b)=>a.year-b.year)}
export async function listSources():Promise<SourceBundle[]>{const files=await listFiles(storagePaths.sources,".json");const sources=await Promise.all(files.map((file)=>readJsonFile<SourceBundle|null>(file,null)));return sources.filter((source):source is SourceBundle=>source!==null).sort((a,b)=>a.date.localeCompare(b.date))}
export async function listMemoryTraceFiles():Promise<MemoryTraceFile[]>{const files=await listFiles(storagePaths.memoryTraces,".json");const traceFiles=await Promise.all(files.map((file)=>readJsonFile<MemoryTraceFile|null>(file,null)));return traceFiles.filter((traceFile):traceFile is MemoryTraceFile=>traceFile!==null).sort((a,b)=>a.date.localeCompare(b.date))}
export async function listMemoryTraces():Promise<MemoryTrace[]>{return (await listMemoryTraceFiles()).flatMap((traceFile)=>traceFile.traces).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))}
export async function readMemoryIndex():Promise<MemoryIndex|null>{return readJsonFile<MemoryIndex|null>(storagePaths.memoryIndex,null)}
export async function readMemoryReport():Promise<MemoryReport|null>{return readJsonFile<MemoryReport|null>(storagePaths.memoryReport,null)}
